### ISSUE TITLE
Add Longest substring without repeating characters

### ISSUE THREAD

**Issue by therohanjaiswal** [dexterpuru/leetcode_java#10]
Given a string s, find the length of the longest substring without repeating characters.

**Example 1:**
> **Input:** s = "abcabcbb"
> **Output:** 3
> **Explanation:** The answer is "abc", with the length of 3.

**Example 2:**
> **Input:** s = "bbbbb"
> **Output:** 1
> **Explanation:** The answer is "b", with the length of 1.

**Example 3:**
> **Input:** s = "pwwkew"
> **Output:** 3
> **Explanation:** The answer is "wke", with the length of 3. Notice that the answer must be a substring, "pwke" is a subsequence and not a substring.

**Example 4:**
> **Input:** s = ""
> **Output:** 0

**Constraints:**
> 0 <= s.length <= 5 * 10<sup>4</sup>
> s consists of English letters, digits, symbols and spaces.

**Comment by dexterpuru** [comment]
@therohanjaiswal  please add question link in the issue description.

**Comment by therohanjaiswal** [comment]
@dexterpuru  done. Shall I start working on this issue?

**Comment by dexterpuru** [comment]
@therohanjaiswal go ahead, open a PR when ever you are ready
