### ISSUE TITLE
Add AsteroidCollision Problem

### ISSUE THREAD

**Issue by Riyagoel2** [dexterpuru/leetcode_java#14]
**Question Link**
https://leetcode.com/problems/asteroid-collision/

We are given an array asteroids of integers representing asteroids in a row.

For each asteroid, the absolute value represents its size, and the sign represents its direction (positive meaning right, negative meaning left). Each asteroid moves at the same speed.

Find out the state of the asteroids after all collisions. If two asteroids meet, the smaller one will explode. If both are the same size, both will explode. Two asteroids moving in the same direction will never meet.

**Comment by dexterpuru** [comment]
@Riyagoel2 please go ahead! and make a PR whenever you are ready.

**Comment by dexterpuru** [comment]
@Riyagoel2 please look at this PR for referance https://github.com/dexterpuru/leetcode_java/pull/12, you will need to submit PR in this format.

**Comment by dexterpuru** [comment]
@Riyagoel2 please also star the repo, it helps in increasing the reach of this repo more open source contributors.
