### ISSUE TITLE
Add code for Longest Palindromic Substring

### ISSUE THREAD

**Issue by YourAKShaw** [dexterpuru/leetcode_java#2]
Leetcode link: [5. Longest Palindromic Substring](https://leetcode.com/problems/longest-palindromic-substring/)

I'd like to work on this issue. Kindly assign it to me.

**Comment by dexterpuru** [comment]
I have assigned it to you, please go ahead!!

**Comment by dexterpuru** [comment]
I saw the PR, i have 2 requests:-
1. As the question is related to string, make a folder in main repo called string, and put the *5. Longest Palindromic Substring* folder in that string folder.
2. You don't need to put 5. in front of the folder's name, only *Longest Palindromic Substring* is enough

**Comment by YourAKShaw** [comment]
Sure thing. I'll get it done.

**Comment by dexterpuru** [comment]
Great work, @Ak-Shaw i hope you could keep contributing, if you show consistency I will make you maintainer for this project

**Comment by YourAKShaw** [comment]
That sounds awesome!! @dexterpuru 
I'll try to give it my best!!
