### ISSUE TITLE
Add Solution for "Largest Number"

### ISSUE THREAD

**Issue by rusyasoft** [dexterpuru/leetcode_java#25]
**https://leetcode.com/problems/largest-number/**
I would like to work on this problem. Please assign it to me

**Comment by YourAKShaw** [comment]
@rusyasoft assigning to you!

**Comment by zatch3301** [comment]
can I contribute...^^

**Comment by YourAKShaw** [comment]
@zatch3301 Sure, follow the contribution guidelines mentioned in README.md. This issue is already assigned though.

**Comment by dexterpuru** [comment]
@rusyasoft please also star the repo, it helps in increasing the reach of this directory to more open source contributors.

**Comment by rusyasoft** [comment]
@Ak-Shaw please check my PR. I have followed your suggestions from (https://github.com/dexterpuru/leetcode_java/pull/37#pullrequestreview-501109533)
