### ISSUE TITLE
Add Solution for "Best Time to Buy and Sell Stock"

### ISSUE THREAD

**Issue by ushachengan** [dexterpuru/leetcode_java#41]
Dynamic Programming: 
https://leetcode.com/problems/best-time-to-buy-and-sell-stock

**Comment by dexterpuru** [comment]
@ushachengan go ahead 👍

**Comment by ushachengan** [comment]
@dexterpuru please review https://github.com/dexterpuru/leetcode_java/pull/45
thanks
