### ISSUE TITLE
Add Solution for "Maximum Depth of N-ary Tree"

### ISSUE THREAD

**Issue by ushachengan** [dexterpuru/leetcode_java#43]
Depth-first Search
https://leetcode.com/problems/maximum-depth-of-n-ary-tree/

**Comment by dexterpuru** [comment]
@ushachengan you are good to go 👍

**Comment by dexterpuru** [comment]
@ushachengan please also star the repo, it helps in increasing the reach of this directory to more open source contributors.

**Comment by ushachengan** [comment]
done! Thanks @dexterpuru

**Comment by ushachengan** [comment]
Hi @dexterpuru, Please review the PR https://github.com/dexterpuru/leetcode_java/pull/52

thanks.
