### ISSUE TITLE
Add solution : JumpGate

### ISSUE THREAD

**Issue by unsaid-u** [dexterpuru/leetcode_java#54]
https://leetcode.com/problems/jump-game/
label - Hacktoberfest2020

**Comment by dexterpuru** [comment]
@BittuRoxs go ahead!!

**Comment by unsaid-u** [comment]
@dexterpuru please accept my PR

**Comment by dexterpuru** [comment]
@BittuRoxs hey I am a bit busy, sorry about that, I will review it tonight.

**Comment by dexterpuru** [comment]
@BittuRoxs you need to make appropriate changes requested by collaborator.

**Comment by unsaid-u** [comment]
@dexterpuru I made all the necessary changes 
Added the solution to problem I have mentioned in this issue 
Jump Game
Please aacept my pull request
