### ISSUE TITLE
Group Anagram

### ISSUE THREAD

**Issue by MayankSingh173** [dexterpuru/leetcode_java#6]
https://leetcode.com/problems/group-anagrams/

**Comment by dexterpuru** [comment]
I have assigned the issue, now you can just add link of this issue to that PR description, or you can make new PR, your choice.

**Comment by MayankSingh173** [comment]
I closed that PR...now I have to fork you repo and add group anagram file, then commit and then push. Then I have to create a new PR....right?

**Comment by dexterpuru** [comment]
make a new branch, after fork and before adding group anagram file, 
And yes then create new PR

**Comment by dexterpuru** [comment]
@MayankSingh173 please also star the repo, it helps in increasing the reach of this repo more open source contributors.
